repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    # ref: https://pre-commit.com/
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: debug-statements
