name: Pre-commit Checks

on:
  pull_request:
    branches:
        - main
    types:
        - opened
        - synchronize
        - reopened

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pre-commit checks
        run: pre-commit run --all-files --show-diff-on-failure
